// Generated by CoffeeScript 1.6.1
var CONTENT_TYPES, fs, http, path, sysout;

http = require('http');

path = require('path');

fs = require('fs');

sysout = console.log;

CONTENT_TYPES = {
  html: 'text/html',
  js: 'text/javascript',
  css: 'text/css',
  png: 'image/png',
  json: 'application/json'
};

http.createServer(function(request, response) {
  var contentType, extname, filePath;
  filePath = '.' + request.url;
  if (filePath === './') {
    filePath = './index.html';
  }
  extname = path.extname(filePath);
  contentType = CONTENT_TYPES[extname.substring(1)];
  return fs.exists(filePath, function(exists) {
    if (exists) {
      return fs.readFile(filePath, function(error, content) {
        if (error) {
          response.writeHead(500);
          return response.end();
        } else {
          response.writeHead(200, {
            'Content-Type': contentType
          });
          return response.end(content, 'utf-8');
        }
      });
    } else {
      response.writeHead(404);
      return response.end();
    }
  });
}).listen(1337);

sysout('Server running at http://127.0.0.1:1337/');
